name: Download and process

on: 
  workflow_dispatch:


jobs:
  build_pages:
    name: Download METS files from Transkribus and convert them to TEIs
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TR_USER: ${{ secrets.TR_USER }}
      TR_PW: ${{ secrets.TR_PW }}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v6
    - name: Install uv with all available options
      uses: astral-sh/setup-uv@v7
    - name: download and transform
      run: uv run download_and_transform.py
    - uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Export and Transformation done
